"""baseline: existing models + file_audit_events

Revision ID: 5a228e071209
Revises: 
Create Date: 2026-09-09 07:28:51.446996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a228e071209'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_request_id'), 'agent_executions', ['request_id'], unique=False)
    op.create_table('file_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_ownership',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_thread_ownership_owner_username'), 'thread_ownership', ['owner_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_ownership_owner_username'), table_name='thread_ownership')
    op.drop_table('thread_ownership')
    op.drop_table('file_audit_events')
    op.drop_index(op.f('ix_agent_executions_request_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
