---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	agent(agent)
	tools(tools)
	billing(billing)
	general(general)
	critic(critic)
	memory_retriever(memory_retriever)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	agent -.-> __end__;
	agent -.-> tools;
	critic -.-> __end__;
	critic -.-> general;
	general --> critic;
	memory_retriever -.-> agent;
	memory_retriever -.-> billing;
	memory_retriever -.-> general;
	router --> memory_retriever;
	tools --> agent;
	billing --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

